'''define all constant here'''


# debug flags
DEBUG_PATH_PLANNING = False
DEBUG_WAYPOINT_TRACKING = True
DEBUG_COLLISIONS = False

# bounds
X_BOUND_LOWER = -3.5
X_BOUND_UPPER =  3.5
Y_BOUND_LOWER = -3.5
Y_BOUND_UPPER =  3.5
Z_BOUND_LOWER =  0.0
Z_BOUND_UPPER =  2.0

# dimensions
DRONE_RADIUS = 0.05
OBSTACLE_RADIUS = 0.06
OBSTACLE_HEIGHT = 1.3

GATE_CENTER_HEIGHT = 1.0
GATE_CENTER_OFFSET = 0.2

GATE_RIM_WIDTH = 0.1
GATE_OPENING_SIZE = 0.4

# take-off and landing
TAKE_OFF_HEIGHT = 0.2
LANDING_HEIGHT  = 0.1

# tracking
WAYPOINT_TRACKING_THRES = 0.2
WAYPOINT_TRACKING_STEP_SIZE = 0.05

SMOOTH_TRACKING_SPEED_MAX = 1.0
SMOOTH_TRACKING_SPEED_MID = 0.5
SMOOTH_TRACKING_SPEED_MIN = 0.3

WAYPOINT_TRACKING_SPEED_MAX = 1.0
WAYPOINT_TRACKING_SPEED_MIN = 0.5

# state machine
FLIGHT_STATE_READY = 0
FLIGHT_STATE_TRACK = 1
FLIGHT_STATE_LANDING = 4
FLIGHT_STATE_OFF = 8

SUB_SAMPLE_DISTANCE = 0.2
NUM_SUB_SAMPLE = 5 # driven by sample distance)

WEIGHT_OF_LENGTH = 3.0
WEIGHT_OF_COLLISION = 2.0
WEIGHT_OF_ACCELERATION = 0.5

MAX_ACCELERATION = 0.5 # (m/s)

POT_PLOT_SUB_TRAJECTORY = False
POT_PLOT_FINAL_TRAJECTORY = True

# robot dimension
ROBOT_RADIUS = 0.05

# clearances
OBSTACLE_SAFETY_FACTOR = 1.25
GATE_SAFETY_FACTOR = 1.1
OBSTACLE_CLEARANCE = 4 * OBSTACLE_RADIUS * OBSTACLE_SAFETY_FACTOR
GATE_EDGE_CLEARANCE = (GATE_RIM_WIDTH + ROBOT_RADIUS) * GATE_SAFETY_FACTOR

# Planner configs

# path planning (potential field)
USE_SMOOTH_TRAJECTORY = False
USE_BIDIRECTIONAL_EXIT = True
USE_LINEAR_COLLISION_LOSS = True

# path planning (FMT)
USE_FMT_SMOOTH_TRAJECTORY = True
USE_FMT_SLIDING_WINDOW = False