'''define all constant here'''

# bounds
X_BOUND_LOWER = -3.5
X_BOUND_UPPER =  3.5
Y_BOUND_LOWER = -3.5
Y_BOUND_UPPER =  3.5
Z_BOUND_LOWER =  0.0
Z_BOUND_UPPER =  2.0

# dimensions
OBSTACLE_RADIUS = 0.06
OBSTACLE_HEIGHT = 1.3

GATE_CENTER_HEIGHT = 1.0
GATE_CENTER_OFFSET = 0.2

GATE_RIM_WIDTH = 0.1
GATE_OPENING_SIZE = 0.4

# take-off and landing
TAKE_OFF_HEIGHT = 0.2
LANDING_HEIGHT  = 0.2

# tracking
WAYPOINT_TRACKING_THRES = 0.05
WAYPOINT_TRACKING_STEP_SIZE = 0.05
WAYPOINT_TRACKING_SPEED = 0.5

# state machine
FLIGHT_STATE_READY = 0
FLIGHT_STATE_TRACK = 1
FLIGHT_STATE_LANDING = 4
FLIGHT_STATE_OFF = 8